#This file provides the source configuration for the sample_data_50k.csv sample data file.
sources:
  - id: clustering
    name: Sample Data 50k
    format: csv
    attributeMappings:
      - canonicalAttribute: sourceRecordId
        sourceAttribute: record_id
      - canonicalAttribute: firstName
        sourceAttribute: given_name
      - canonicalAttribute: middleName
        sourceAttribute: middle_name
      - canonicalAttribute: lastName
        sourceAttribute: sur_name
      - canonicalAttribute: mobilePhone
        sourceAttribute: phone
      - canonicalAttribute: homePhone
        sourceAttribute: phone2
      - canonicalAttribute: emailAddress
        sourceAttribute: email
      - canonicalAttribute: emailAddress
        sourceAttribute: email2
      - canonicalAttribute: dateOfBirth
        sourceAttribute: dob
      - canonicalAttribute: postalCode
        sourceAttribute: zip
      - canonicalAttribute: streetAddress
        sourceAttribute: street_address
      - canonicalAttribute: city
        sourceAttribute: city
      - canonicalAttribute: governingDistrict
        sourceAttribute: state
      - canonicalAttribute: ipAddress
        sourceAttribute: ip_address
      - canonicalAttribute: accountId
        sourceAttribute: loyalty_id
